### ISSUE TITLE
MultiAuthentication with BasicAuthentication and Authentication does not work as expected

### ISSUE THREAD

**Issue by capooti** [django-tastypie/django-tastypie#1390]
I would like to combine Authentication and BasicAuthentication with MultiAuthentication, like this:

authentication = MultiAuthentication(BasicAuthentication(),Authentication(),)

When not using basic authentication the API would return objects that are visible to the anonymous user. When using basic authentication the API would return objects visible to a specific user plus the ones visible to the anonymous user.
Unluckily when trying to access the API using Firefox with a url such as:
http://user:password@localhost:8000/myapp/api/v2.4/mymodel/?format=json&limit=10

Firefox complains that 
"You are about to log in to the site "localhost" with the username "opweb", but the website does not require authentication. This may be an attempt to trick you." 

any idea what could be wrong here?

Note that using curl everything works perfectly, but from the browser and from an external application I am getting this behavior.

**Comment by SeanHayes** [comment]
It's because you've put the credentials right in the URL. Firefox is warning you because malicious sites could put anchor tags containing their best guess of your credentials for other sites, hoping you'll click. The reason the warning message says "the website does not require authentication" is because you sent the credentials right off the bat, before Firefox had a chance to receive a WWW-Authenticate response header.

**Comment by capooti** [comment]
No, the issue is still there, try it with curl.
thanks

**Comment by SeanHayes** [comment]
Earlier you said it worked "perfectly" in curl but gave an error in Firefox, citing a Firefox specific error message that is known to only happen when credentials appear in the URL.

Also, our auth classes check the Authorization header, but not the username or password section of a URL. It's not something we're going to support because of how insecure it is.
