### ISSUE TITLE
kwargs['id'] for custom view return more than one resource in tastypie 13.3

### ISSUE THREAD

**Issue by aldarund** [django-tastypie/django-tastypie#1452]
I have following code:
  ```
  def prepend_urls(self):
        return [
            url(r"^(?P<resource_name>%s)/me/?$" % self._meta.resource_name, self.wrap_view('me')),
            ....
        ]

    def me(self, request, *args, **kwargs):
        self.is_authenticated(request)
        kwargs['id'] = request.user.id
        return self.dispatch_detail(request, **kwargs)
```

And it stopped working in last tastypie release, and was working in 13.1. In latest tastypie it just returns:
More than one resource is found at this URI.

If i change kwargs['id'] to kwargs['pk'] - it begin to work.
Is there something wrong with code or its a bug?

**Comment by SeanHayes** [comment]
Some changes were made to make filtering on obj_get more consistent with filtering on obj_get_list. Whereas before you could filter on any model field, now you can only filter on configured filters and Meta.detail_uri_name.

I'll update the docs with a recommendation to always use whatever Meta.detail_uri_name is set to instead of hard coding 'id' when writing custom code.

**Comment by aldarund** [comment]
Thats a pretty breaking change for a minor release...

**Comment by SeanHayes** [comment]
Yeah, you might be right. The whole versioning scheme is a little off since we're still pre-1.0. The introduced changes fixed several other issues and improved security so I wanted to get it into the 0.13.x series. Some upcoming changes in future versions might prevent devs from upgrading easily, so I wanted to make those fixes available.

From now on I'll try to divide up our changes into more major releases, rather than trying to squeeze them into a current release series.
