### ISSUE TITLE
Release notes out-of-date

### ISSUE THREAD

**Issue by elitzer2** [django-tastypie/django-tastypie#1586]
Can someone update the release notes in the docs: https://django-tastypie.readthedocs.io/en/latest/release_notes/index.html

We are trying to figure out what changed in the latest two releases (0.14.1-2) and whether or not we need to upgrade. Thanks! Is it really just Django 2.0/2.1 support?

Update: Oh that's weird, I see it committed: https://github.com/django-tastypie/django-tastypie/commit/b99c621191f51b56f828ac5affd58d9817d2096e

Not sure how it all syncs up with readthedocs.io

**Comment by georgedorn** [comment]
At some point RTD stopped updated automatically, and the TastyPie docs aren't attached to my account there.  I'll contact RTD to see what can be done.

In the meantime, the releases page contains broad releases notes, and more specific changelogs can be found in docs/release_notes in the repo itself: https://github.com/django-tastypie/django-tastypie/tree/master/docs/release_notes

**Comment by georgedorn** [comment]
@toastdriven @SeanHayes I'm not sure who controls the RTD project at this point; if one of you has access, can you add me so I can take care of this problem?  My RTD username is 'GDorn'.

**Comment by SeanHayes** [comment]
@georgedorn Done

**Comment by georgedorn** [comment]
RTD inexplicably started building again.  It was having a build error that was fixed by forcing a wipe and rebuild, but that doesn't really explain how 0.14.1 got marked inactive and why release notes were missing for a while there.

But it appears everything is building again, and the missing release notes are available again, here:
https://django-tastypie.readthedocs.io/en/v0.14.2/release_notes/index.html
