### ISSUE TITLE
docs need to be rebuilt for 0.14.3 release

### ISSUE THREAD

**Issue by nikolas** [django-tastypie/django-tastypie#1612]
The docs on readthedocs are out of date, and need to be rebuilt. See: https://django-tastypie.readthedocs.io/en/latest/

For example, in the [Release notes](https://django-tastypie.readthedocs.io/en/latest/release_notes/index.html), there is no entry for 0.14.3 even though there's a new doc for it here: https://github.com/django-tastypie/django-tastypie/blob/master/docs/release_notes/v0.14.3.rst

**Comment by georgedorn** [comment]
Turns out RTD just wasn't noticing new tags automatically; I had the same problem with v0.14.4.  When that tag was released, something I did triggered the build for v0.14.3.

Manually rebuilding 'master' or 'latest' a couple times will eventually (probably?) get it to notice missing tags, but it never seems to do this automatically.
