### ISSUE TITLE
Questions about TastyPie future

### ISSUE THREAD

**Issue by StefanMich** [django-tastypie/django-tastypie#1653]
I apologize for this not being an actual issue, but the communication channels presented in the readme seemed dead, so it seemed more likely to get an answer here. 
This is probably mostly aimed at @georgedorn  as you are the only maintainer (as far as I can tell). Feel free to contact me via my email if you prefer.

I am representing Intempus, a danish company using Tastypie for our API. We are currently evaluating whether or not to move away from Tastypie, and have for now decided that moving away (for example to DRF) would take much more work than we would actually benefit from it. 
One concern is how the future looks for Tastypie. It seems that apart from being mostly stable, the codebase has been almost stagnant for years, apart from updating django compatibility. We are interested in knowing how you see the codebase evolving? Will there be continued bug fixing, added features, django compatibility and security audit/updates?

We would possibly be open to support the project financially and also with active development on the project, but it would require that someone with deep knowledge of the project is still interested in being active.

**Comment by georgedorn** [comment]
I'll contact you via email, but anybody else in a similar situation might find this short version useful:
- I attempt to keep tastypie compatible with the last two LTS releases and non-LTS releases between those.  Sometimes I do that myself, sometimes I take PRs when somebody else needs it ASAP - I get around to it a week or three after django updates, generally.
- We haven't had a security audit that I'm aware of, outside of some issues that came up very early in the project's development.  The security discussion mailing list still exists but hasn't had a security issue reported to it in probably a decade.
- Serious bugs are actually fairly rare, as far as I can tell.  A big part of this is the core being basically done and stable; most of the bugs come out around update time, either as regressions in the compatibility changes or long-standing issues revealed due to a change in how django behaves.
