### ISSUE TITLE
Release Django 5 compatible version

### ISSUE THREAD

**Issue by pg1671** [django-tastypie/django-tastypie#1668]
Tastypie doesn't work with django 5.0 due to importing deprecated datetime functions.

Can you merge the django 5 fixes so it can released on the main branch.

**Comment by georgedorn** [comment]
The django 5 fixes were merged two weeks ago.  I have not yet published the release to PyPI, as a couple other PRs are in the works and the datetime-related changes were difficult, if not impossible, to develop unit test scenarios for.  I am hoping some users will have run their own code against the main branch and report back, but I will publish to PyPI next week.

**Comment by Fl0r14n** [comment]
any update on the release?

**Comment by jonatkinson** [comment]
Hey @georgedorn, we have recently ticked over 6 months since the last release to PyPI, and no commits to the project for some time.

Is the project on stable ground? My organisation relies on Tastypie for a significant project, and we will gladly contribute time and resources towards Django 5.0 support.
