### ISSUE TITLE
Make the format not implemented error more descriptive

### ISSUE THREAD

**Issue by jleclanche** [django-tastypie/django-tastypie#629]
Hi, I recently hit the "format not implemented" error as I'm sure many people have. Given that the [explanation](http://django-tastypie.readthedocs.org/en/v0.9.11/debugging.html#i-m-getting-xml-output-in-my-browser-but-i-want-json-output) for it is non-obvious, I suggested on IRC making the error more descriptive, the likes of:

```"Sorry, support for <dump accept header here> is not implemented yet. Please append "?format=json" to your URL."```

Just a thought.

**Comment by SiggyF** [comment]
I also get this error message if I use curl and add text/html as an accepted mime type. 
I would suggest to remove the [http](https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/serializers.py#L86) from the list of supported formats. The list of supported formats is passed to the [best_match](https://github.com/dbtsai/python-mimeparse/blob/master/mimeparse.py#L137) function. Because tastypie passes `text/html` to the list of supported formats it will return `text/html` as the preferred format (because it has the default [q=1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)), but it is in fact not supported (yet). 

This is an example of a curl request that fails, even though it supports json:
```
curl -H "Accept: application/json;q=0.9,text/html" http://localhost:8000/api/v1/
```

I'd be happy to put this in a pull request if that would work for you?

**Comment by SeanHayes** [comment]
@SiggyF That would be great! Make sure to add tests.

**Comment by SeanHayes** [comment]
The related PR has been merged. Another PR including a more descriptive error message would still be welcome, if you're interested.
